config/routes.rb
StoreMediumClass::Application.routes.draw do
  resources :products

  root 'products#index'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row collapse">
  <div class="small-3 columns">
    <%= f.label :name, class: "right inline" %>
  </div>
  <div class="small-9 columns"><%= f.text_field :name %></div>
</div>
<div class="row collapse">
  <div class="small-3 columns">
    <%= f.label :price, class: "right inline", title: "Price in USD", data: {tooltip: true} %>
  </div>
  <div class="small-9 columns"><%= f.text_field :price %></div>
</div>

<div class="row collapse">
  <div class="small-9 small-offset-3 columns"><%= f.submit class: "button small radius" %></div>
</div>

<% end %>

app/views/products/edit.html.erb
<div class="small-9 small-offset-3 columns"><h1>Editing product</h1></div>


<%= render 'form' %>

<!--<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>-->

<div class="row collapse">
<div class="small-9 small-offset-3 columns">
<%= link_to 'Show', @product, class: "button radius small mart-left" %> |
<%= link_to 'Back', products_path, class: "button radius small mart-right" %>
</div>
</div>

app/views/products/index.html.erb
<h1>Listing products</h1>
<table class="responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, class: "small button radius" %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "small button radius" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "small button radius tablestyle" %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Product', new_product_path, class: "small button radius" %>

app/views/products/new.html.erb
<!--<div class="row collapse">-->
<div class="small-9 small-offset-3 columns"><h1>New product</h1></div>
<!--</div> -->

<%= render 'form' %>

<div class="row collapse">
  <div class="small-9 small-offset-3 columns"><%= link_to 'Back', products_path, class: "button small radius" %></div>
</div> 

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row collapse">
<div class="small-9 small-offset-3 columns">
  <h1> Product </h1>
</div>
</div>



<!--
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


<span>
  <strong>Price: </strong>
  <%= @product.price %> <input type='text' name='fname' value= "<%= @product.price %>" readonly />
</span>

<p>
  <strong>Price: </strong>
  <%= @product.price %> <input type='text' name='fname' value= "<%= @product.price %>" readonly />
</p>

<input type='text' name='fname' value= "<%= @product.price %>" readonly  />

<p class="formfield">
    <label for="textarea">Label for textarea</label>
    <textarea id="textarea" rows="2"><%= @product.price %></textarea>
</p>



<%= link_to 'Edit', edit_product_path(@product), class: "button radius small mart-left" %> |
<%= link_to 'Back', products_path, class: "button radius small mart-right" %>

-->

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row collapse">
  <div class="small-3 columns">
    <%= f.label :name, class: "right inline" %>
  </div>
  <div class="small-9 columns"><%= f.text_field :name %></div>
</div>
<div class="row collapse">
  <div class="small-3 columns">
    <%= f.label :price, class: "right inline bold", title: "Price in USD", data: {tooltip: true} %>
  </div>
  <div class="small-9 columns"><%= f.text_field :price %></div>
</div>


<div class="row collapse">
<div class="small-9 small-offset-3 columns">
	<%= link_to 'Edit', edit_product_path(@product), class: "button radius small mart-left" %> |
	<%= link_to 'Back', products_path, class: "button radius small mart-right" %>
</div>
</div>


<% end %>